#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)

#### Set cran repository to use ####
if (length(args)==0) {
   stop("Must supply arg of 'latest', or of snapshot date in format 'yyyy-MM-dd'", call.=FALSE)
}
snapshot_version <- args[1]
print(sprintf('snapshot_version = %s', snapshot_version))
repo <- if(snapshot_version == 'latest') 'https://cran.r-project.org/' else sprintf('https://cran.microsoft.com/snapshot/%s/', snapshot_version)
print(sprintf('Installing from %s', repo))
options(repos = c(CRAN = repo))

#### Install packages ####
install.packages("sparklyr")
install.packages('base64enc')
install.packages('crayon')
install.packages('DBI')
install.packages('devtools')
install.packages('digest')
install.packages('evaluate')
install.packages('haven')
install.packages('highr')
install.packages('htmltools')
install.packages('htmlwidgets')
install.packages('httpuv')
install.packages('jsonlite')
install.packages('keyring')
install.packages('knitr')
install.packages('later')
install.packages('markdown')
install.packages('mime')
install.packages('miniUI')
install.packages('mongolite')
install.packages('odbc')
install.packages('openssl')
install.packages('packrat')
install.packages('plumber')
install.packages('png')
install.packages('profvis')
install.packages('promises')
install.packages('r2d3')
install.packages('R6')
install.packages('RCurl')
install.packages('readr')
install.packages('readxl')
install.packages('reticulate')
install.packages('rJava')
install.packages('RJDBC')
install.packages('rlang')
install.packages('rmarkdown')
install.packages('RODBC')
install.packages('rprojroot')
install.packages('rsconnect')
install.packages('RSQLite')
install.packages('rstudioapi')
install.packages('shiny')
install.packages('shinytest')
install.packages('sourcetools')
install.packages('stringi')
install.packages('stringr')
install.packages('testthat')
install.packages('xml2')
install.packages('xtable')
install.packages('yaml')
