version: "3.4"

services:
  databricks-cli:
    container_name: databricks-cli
    build: .
    environment:
        - DATABRICKS_HOST="https://westeurope.azuredatabricks.net"
        - DATABRICKS_TOKEN="ADD_PAT_HERE"

#Copy this file and name it 'docker-compse.yml', then add your Databricks PAT
# To generate a token: https://docs.databricks.com/dev-tools/api/latest/authentication.html